### ISSUE TITLE
account for the custom return URL for paypal express

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-conditional-success-redirects#7]
There's a conflict with PayPal Express where CSR forces the customer to be redirected to the purchase confirmation page from PayPal. With PayPal Express, they should be redirected to a confirmation page instead. Then from the confirmation page, they can be redirected to purchase confirmation (of wherever).

With the current behavior, the payment record is left as `Pending` and the transaction is never confirmed.

**Comment by pippinsplugins** [comment]
@SDavisMedia I just tested this and it worked properly for me.

Could you try it again? Maybe your PayPal Pro / Express plugin was out of date?

**Comment by SDavisMedia** [comment]
Everything is fine for me as well. I can no longer replicate what I described before, even on an older tag. Not sure what was up but all is well.

**Comment by pippinsplugins** [comment]
Woot!

**Comment by pippinsplugins** [comment]
New case of this occurring: https://secure.helpscout.net/conversation/691995910/92766?folderId=180505

**Comment by pippinsplugins** [comment]
Tracked it down. Only happens when PayPal Express through Recurring Payments is used.

Note: this also causes the payment records and subscriptions to not be created.

**Comment by pippinsplugins** [comment]
Fixed it!

**Comment by SDavisMedia** [comment]
@pippinsplugins Something broke with this release. I've rolled the product back to 1.1.3 on EDD Site.

To replicate on 1.1.4 (`master`), just complete a basic purchase with Test Payment gateway. The purchase confirmation page should result in a redirect error: https://cl.ly/d634e7066096

I have no errors in my debug log. Both @misulicus and I have replicated, and he has a ticket reporting the issue. The guy from your previous ticket has not replied since you told him to update yesterday.

Neither of us can fully understand the code change from the last update, so we're stuck between reverting and fixing it since they both present a bug to users.

I'm available for replicating, testing, and facilitating a quick release of 1.1.5.

**Comment by pippinsplugins** [comment]
Took a bit to figure out what was happening but got it.

The problem was caused by `get_redirect()` returning the standard success page URL by default, even when no custom redirect was active.

This became a problem because the change I made previously slightly adjusted the behavior of the `process_offsite_payment()` so that a redirect was only prevented when on the confirmation page for PayPal Express. Doing this caused `process_offsite_payment()` to always trigger a redirect when using non-PayPal Express gateways. The redirect that occurred was trying to send the user to the same page they were already on, which then turned into an infinite loop.

The problem didn't occur previously because the `process_offsite_payment()` never actually triggered a redirect, it only _appeared_ to trigger a redirect.

To resolve the problem, I have:

1. Updated `process_offsite_payment()` to only send a redirect when not on the PayPal Express confirmation pages
2. Updated `get_redirect()` to return `false` when no custom URL is needed, allowing us to detect if a redirect should occur at all

To test the fix (repeat with recurring and non-recurring products):

1. Checkout `issue/7-2`
2. Enable at least one custom redirect
3. Enable PayPal Express and Recurring Payments
4. Add a product to the cart that does _not_ have a custom redirect
5. Use the Test Gateway to complete the purchase. Confirm redirect page is correct.
6. Add a product to the cart that does _not_ have a custom redirect
7. Complete purchase with PayPal Express. Confirm redirect page is correct.
8. Add a product to the cart that _does_ have a custom redirect.
9. Complete the purchase with Test Gateway.  Confirm redirect page is correct.
10. Add product to the cart that _does_ have a custom redirect. 
11. Complete the purchase with PayPal Express gateway.  Confirm redirect page is correct.

Repeat steps above for both recurring and non-recurring products.

**Comment by SDavisMedia** [comment]
All 8 scenarios are working perfectly in my testing. 👌

**Comment by pippinsplugins** [comment]
:100:
